### ISSUE TITLE
FlyTour 3.0.0

### ISSUE THREAD

**Issue by JameChen** [mxdldev/android-mvp-mvvm-flytour#11]
FlyTour 3.0.0怎么报错呀少了com.fly.tour.me.inject.component里面的文件

**Comment by mxdldev** [comment]
缺少依赖包，在NewsTypeListActivity和NewsDetailAddActivity 加上import java.util.List; 然后在编译就好了

**Comment by JameChen** [comment]
编译现在是可以了但是运行mainmodule报错 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fly.tour.main/com.fly.tour.main.SplashActivity}: com.alibaba.android.arouter.exception.InitException: ARouter::Init::Invoke init(context) first!
    at com.fly.tour.common.base.BaseActivity.onCreate(BaseActivity.java:56)
        at com.fly.tour.common.base.BaseMvpActivity.onCreate(BaseMvpActivity.java:27)
        ARouter.getInstance().inject(this);
